spring.application.name=pansauce
spring.datasource.url=jdbc:ucanaccess://./src/main/resources/PanSauce.accdb;openExclusive=false;ignoreCase=true
spring.datasource.driver-class-name=net.ucanaccess.jdbc.UcanaccessDriver
server.servlet.session.timeout=120m