spring.application.name=pansauce
spring.datasource.url=jdbc:ucanaccess://./src/main/resources/PanSauce.accdb;openExclusive=false;ignoreCase=true
spring.datasource.driver-class-name=net.ucanaccess.jdbc.UcanaccessDriver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=0
spring.datasource.hikari.max-lifetime=10800000
spring.datasource.hikari.keepalive-time=300000
jwt.secret=accaba52683ddbad055c9a37f0ad39f2dc658f132d9ce178b22ebae339c2a74b