spring.application.name=pansauce
spring.datasource.url=jdbc:ucanaccess://C:/Users/ihate/IdeaProjects/pansauce/src/main/resources/PanSauce.accdb;openExclusive=false;ignoreCase=true
spring.datasource.driver-class-name=net.ucanaccess.jdbc.UcanaccessDriver